### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by kode30** [kode30/install-bootcamp#1]
Problema con Disco AWS no montado

**Comment by kode30** [comment]
Solucionado
lsblk
file -s /dev/nvme1n1
mkfs -t ext4 /dev/nvme1n1
mkdir /clouderadata
mount /dev/nvme1n1 /clouderadata

**Comment by kode30** [comment]
Problemas Permisos Iniciar YARN, Zookeper

**Comment by kode30** [comment]
Solucionado
Se debe cambiar los permisos y asignar la ruta de usuarios correspondientes:

$ ls -l /var/lib/ |grep hadoop
drwxr-xr-x  5 hdfs         hdfs         4096 Sep  1 13:54 hadoop-hdfs
drwxr-xr-x  2 httpfs       httpfs         75 Jul  7 14:50 hadoop-httpfs
drwxr-xr-x  2 kms          kms            59 Jul  7 14:50 hadoop-kms
drwxr-xr-x  2 mapred       mapred         75 Jul  7 14:50 hadoop-mapreduce
drwxr-xr-x  4 yarn         yarn          130 Jul 10 10:18 hadoop-yarn

**Comment by rafaelarana** [comment]
Great job!!!!
