### ISSUE TITLE
Storage Lab

### ISSUE THREAD

**Issue by kode30** [kode30/install-bootcamp#2]

**Comment by kode30** [comment]
Falta ejercicio 1 (a la espera del compañero)

**Comment by kode30** [comment]
ok

**Comment by rafaelarana** [comment]
Comprueba el tamaño que generas en el Teragen - Debería ser  10 GB y creo que generas 100 MB.

**Comment by kode30** [comment]
Hola Rafa si lo hice a propósito jeje es que no tengo espacio en los servidores tengo solo dos disco de 25gb y voy justo jejeje... Si el viernes hay que hacerlo creare las máquinas con suficiente espacio para poner la cantidad que pidan

Saludos

Rafael Caballero
Head of Big Data & A.I
Logicalis Spain

T: +34 933 632 590
M: +34 673 035 786

Avda. Diagonal, 569, 2ª planta
08029 Barcelona
www.es.logicalis.com 
______________________________________ 
Business and technology working as one




   Rafael Arana --- Re: [kode30/install-bootcamp] Storage Lab (#2) --- 
    De:"Rafael Arana" <notifications@github.com>A:"kode30/install-bootcamp" <install-bootcamp@noreply.github.com>Cc:"kode30" <rafael.caballero@es.logicalis.com>, "State change" <state_change@noreply.github.com>Fecha:jue., 14 feb. 2019 0:13Asunto:Re: [kode30/install-bootcamp] Storage Lab (#2)
  
  Comprueba el tamaño que generas en el Teragen - Debería ser 10 GB y creo que generas 100 MB.

**Comment by rafaelarana** [comment]
OK
